const bonusEn = `
## **What are the general bonus rules?**

Bonuses are to be enjoyed as an extension of a customer’s playing experience and should be enjoyed as such. We reserve the right to review any customer account to ensure game play is within these generally accepted guidelines.

We reserve the right to revoke and/or cancel any bonuses we judge may have been obtained by misuse of the system.

We may vary or cancel any promotion or bonus at any time. We shall incur no liability and no bonus or payment of any kind will be awarded.

We reserve the right, at our sole discretion, not to issue refunds of any deposits, remittance of balances or winnings generated and bonuses on the account, should we suspect any kind of bonus abuse has occurred. Abuse includes but is not limited to, opening multiple accounts to claim additional bonuses or benefits.

For any promotion, including but not limited to welcome bonus offers, specific bonus terms and conditions shall apply.

You are not permitted to transfer any bonuses.

We reserve the right to request proof of your identity, age and origin of funds at any time, prior to crediting your account with a bonus.

If you make a withdrawal request, you will forfeit all of your bonuses (which includes, without limitation,, Free Spins).

We may withdraw, revoke or amend any promotion at any time for any reason. We shall incur no liability and no bonus or payment will be awarded

You are eligible for one bonus per campaign.

We reserve the right to change the structure of the bonus program at any time.

## **Use of Free Spins**

The terms above and the following terms and conditions shall apply to you use of Free Spins:

1. The terms of claiming any Free Spins shall be detailed in an email sent to you by us or in the relevant promotion terms (as applicable).
2. All free spins credited to your account, will expire as detailed in an email sent to you by us or in the relevant promotion terms (as applicable) and any unused free spins automatically expire and will be removed from your account.
3. Free Spins may only be used on certain games as detailed in an email sent to you by us or in the relevant promotion terms (as applicable).
4. If you are not the intended recipient of the email with respect to the granting of Free Spins then the Free Spins offer is null and void.

## **Poker Bonus**

Engaging in **online poker games** and **tournaments** offers a pathway to **win poker cash prizes**, blending skill with the excitement of virtual gameplay.

WPT Global, as the **[best poker software and app](https://wptglobal.com/poker-download)**, not only facilitates seamless gameplay but also provides access to a variety of formats, including **online and live poker tournaments** and **cash games**, ensuring that enthusiasts can find their niche within the poker ecosystem.

### **Poker Deals**

For those aiming to elevate their game, participating in **online poker tournaments** represents a chance to test their mettle against a global pool of talent. The blend of strategic play, the pursuit of **online poker promotions and bonuses**, and the convenience of the **best poker app** options creates a dynamic environment where skill, strategy, and luck intertwine, offering a comprehensive poker experience for players at all levels.

### **Real Money Poker Rakeback**

A [poker rakeback](https://wptglobal.com/how-to-play/poker-glossary#letter-r) is a form of reward system offered by some online poker rooms or through third-party affiliates to players. It involves returning a portion of the rake (the fee taken by the poker room from each pot or tournament entry fee) back to the players who generate it. Rakeback is typically offered as a percentage of the rake generated by the player's participation in cash games or tournaments.
`;

export default bonusEn;
